##
# DB migration
##
flyway:
  enabled: true

##
# Healht endpoint (/health) configruation
##
endpoints:
  health:
    sensitive: false

##
# DB connection
##
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: *
    username: *
    password: *
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  hibernate:
    show_sql: true
    hbm2ddl.auto: validate